# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=release
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),release)
  CalDict_config = release
  SabreRecon_config = release

else ifeq ($(config),debug)
  CalDict_config = debug
  SabreRecon_config = debug

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := CalDict SabreRecon

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

CalDict:
ifneq (,$(CalDict_config))
	@echo "==== Building CalDict ($(CalDict_config)) ===="
	@${MAKE} --no-print-directory -C . -f CalDict.make config=$(CalDict_config)
endif

SabreRecon: CalDict
ifneq (,$(SabreRecon_config))
	@echo "==== Building SabreRecon ($(SabreRecon_config)) ===="
	@${MAKE} --no-print-directory -C . -f SabreRecon.make config=$(SabreRecon_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f CalDict.make clean
	@${MAKE} --no-print-directory -C . -f SabreRecon.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  release"
	@echo "  debug"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   CalDict"
	@echo "   SabreRecon"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"